### PR TITLE
Update readme to better explain what sanitizer/desanitizer does

### PR DESCRIPTION
**Pull request by jadekler**
[Issue #14]

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@jadekler Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cloudops/secrets-sanitizer&pullRequestId=17)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=pivotal-cloudops/secrets-sanitizer&pullRequestId=17) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by jadekler** [comment]
CLA signed

**Comment by pivotal-issuemaster** [comment]
@jadekler Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cloudops/secrets-sanitizer&pullRequestId=17)!

**Comment by pivotal-issuemaster** [comment]
@jadekler Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=pivotal-cloudops/secrets-sanitizer&pullRequestId=17)!

**Comment by supertopher** [comment]
@jadekler can you check the readme on master and see if this helps to address this PR / issue?

thanks!

**Comment by chentom88** [comment]
(jean here) 👍  looks good @supertopher, dig the 'reverse the process' bits

**Pull request closed without merging**
